### ISSUE TITLE
Use Gson to convert Bank Accounts to JSON

### ISSUE THREAD

**Issue by rpmartz** [patrickatcw/JavaBanco#10]
We have the beginnings of a very basic bank in that we can create accounts and transfer money between them. One problem though is that the accounts are ephemeral - they only exist for a short amount of time while you're running the `main` method from your `Main` class. We need to begin to evolve our solution so that we have a way to keep track of account balances over time.

The first step is to provide a machine-readable way to represent account data. The simplest format is JSON, which stands for Java Script Object Notation. You probaby used this in your Node.js work. 

Every programming language has a way to convert objects to JSON or to convert JSON to objects. One of the most popular libraries in the Java world is one called Gson that was written and is maintained by Google. You can check out the source code [here](https://github.com/google/gson). 

There are two parts to this task:

1. Add Gson as a dependency in `pom.xml`. [Instructions here](https://github.com/google/gson/blob/master/UserGuide.md#using-gson-with-maven). This will allow you Note that we already have a `<dependencies>` element in or `pom.xml`, so you just need to add the part that starts with `<dependency>` and ends with `</dependencies>`. 

2. Add a new class called `GsonPrinter` with a `main()` method that creates a new `BancAccount` object and then uses Gson to print it out as JSON. [Example here](https://github.com/google/gson/blob/master/UserGuide.md#using-gson-with-maven). This is what your output should look like: 

```json
{"accountName":"Ryan\u0027s Account","balance":10000,"accountNumber":2}
```

(Don't worry about the `\u0027`, that's the Unicode character for an apostrophe).

**Comment by patrickatcw** [comment]
completed issue and sent a pull request.
