### ISSUE TITLE
Add TravisCI integration

### ISSUE THREAD

**Issue by rpmartz** [patrickatcw/JavaBanco#12]
Ok, so now we've got ourselves a basic bank and some unit tests. Now, we need to make sure we keep ourselves honest and not commit broken code. 

We're going to integrate our project with a service called [Travis CI](https://travis-ci.org/). The "CI" part stands for _continuous integration_. You can read about it [here](https://en.wikipedia.org/wiki/Continuous_integration). 

If you ask 5 developers what CI is, you'll probably get 4 different answers, so don't worry too much about it the granular details, but one of the tenants of it is having a build server that runs a full build and test suite every time anyone checks anything in. This helps compiler errors, test failures, and when done well bugs immediately after you commit them rather than later in the process.

Travis is a CI service that's free for public repositories. There are a ton of other services out there, but Travis plays nicely with GitHub so we can use that. Once it's set up, any time you push commits to GitHub, it will automatically kick off a Travis build and if you have any build or test failures it will send you an email. On a team, you can configure your CI server to send everyone an email. This is a strong incentive both to make sure you test your code before you check it in but also to make sure you fix problems as soon as they happen. 

There are instructions for how to use Travis for a Java project [here](https://docs.travis-ci.com/user/languages/java/). Give it a whirl and let me know if you have any major issues.

**Comment by patrickatcw** [comment]
build was successful, updated branches
