### ISSUE TITLE
Write BankAccounts to file in JSON format. 

### ISSUE THREAD

**Issue by rpmartz** [patrickatcw/JavaBanco#13]
Now that you know how to convert a `BancAccount` object to a `String` of JSON, we need to go ahead and write it to file so that the program can read the account information the next time we run it.

Look up how to create a file ([here's the Oracle tutorial](https://docs.oracle.com/javase/tutorial/essential/io/file.html) but feel free to use whatever resources you like best.  Note that you'll see that there are multiple ways of creating a file; for our example it doesn't really matter which you use, so go with whatever one is easiest for you to understand.

Modify your `GsonPrinter` class to write the JSON strings to a file. 

Hint: In order to read the bank accounts back from the file, you'll need to write them as a JSON array. In other words, this is what the file contents should look like with two bank accounts:

```json
[
    {
        "accountName": "Ryan\u0027s Account",
        "balance": 10000,
        "accountNumber": 2
    },
    {
        "accountName": "Patrick\u0027s Account",
        "balance": 10000,
        "accountNumber": 3
    }
]
```

Gson will take care of this for you, but you'll need to add them to a `List<BancAccount>` and then pass that list to the `gson.toJson()` method.

Something like this:

```java
// set up accounts and Gson

List<BancAccount> accounts = new ArrayList<>();
accounts.add(accountOne);
accounts.add(accountTwo);

String json = gson.toJson(accounts);
```

**Comment by patrickatcw** [comment]
created new file and wrote accounts to file
