### ISSUE TITLE
Read bank accounts back into program from file

### ISSUE THREAD

**Issue by rpmartz** [patrickatcw/JavaBanco#14]
After you get the previous issue completed, the next step is to read the JSON file  back in. This is analogous to reading info from the database, which we'll get to here shortly. 

Basically, if you have this JSON in a file:

```json
[
    {
        "accountName": "Ryan\u0027s Account",
        "balance": 10000,
        "accountNumber": 2
    },
    {
        "accountName": "Patrick\u0027s Account",
        "balance": 10000,
        "accountNumber": 3
    }
]
```

You can use GSON to read that file and then you will have a `List<BancAccount>` of those accounts that would be the same as doing this:

```java
BancAccount acct1 = new BancAccount();
acc1.setName("Ryan's Account");
// other setters for acct1

BancAccount acc2 = new BancAccount();
// setters for acct2
```

But you don't have to do any of that, GSON takes care of it when it reads the JSON.

**Comment by rpmartz** [comment]
In your research  (Google "how to read file Gson") you will see that Gson has a `fromJson` method that takes either a `Class` or a `Type`.  This is a little bit tricky for a `List<BancAccount>`, so I'm going to tell you the answer and later on we'll go over what it means. So, it'll look like this:

```java
// read the file contents into  a string <-- you have to write code to do this part
Type accountListType = new TypeToken<List<BancAccount>>() {}.getType();

Gson gson = new Gson();
List<BancAccount> accounts = gson.fromJson(stringFromFile, accountListType)'
```

**Comment by patrickatcw** [comment]
complete
