### ISSUE TITLE
SQL Part I: Create the JavaBanco database and schema in MySQL.

### ISSUE THREAD

**Issue by rpmartz** [patrickatcw/JavaBanco#18]
We'll start simple and evolve JavaBanco as we go. 

We'll need to create a database and add a table for our bank accounts. You can call the database whatever you want (`javabanco` is a good candidate).

In the `javabanco` database, make a table called `bank_account` with the following columns:

* `account_name` that is a `varchar(255)`
* `balance` that is a `decimal(10, 2)`
* `account_number` that is a `bigint(20)`

Make `account_number` the primary key.

**Comment by patrickatcw** [comment]
javabanco database created, with table and columns
