### ISSUE TITLE
SQL Part III: Write some queries

### ISSUE THREAD

**Issue by rpmartz** [patrickatcw/JavaBanco#20]
Write the following SQL queries:

* Return all records in the table
* Return a single record by account number
* Find all accounts with a balance above $500
* Find all accounts with a balance below $500
* Find only the list of account names with a balance above $500
* Find all account numbers and balances, ordered from highest balance to lowest balance
* Find a list of account names, ordered from lowest balance to highest balance

You can make a `src/main/resources/sql` directory so that you can check these into source control

**Comment by patrickatcw** [comment]
mysql work completed and pushed to branch
