### ISSUE TITLE
JDBC Part I: Add MySQL to Maven

### ISSUE THREAD

**Issue by rpmartz** [patrickatcw/JavaBanco#21]
Ok, so now you've got some dummy data and you've written some queries. You have been using MySQL Workbench to query the database, but your app won't be able to use MySQL Workbench to read or write data to the database. 

The API for accessing databases from Java is called JDBC, which stands for Java Database Connectivity. It's a standard that allows Java code to be used with different kinds of databases, so that regardless of whether your application uses a PostgreSQL, MySQL, or Oracle database, your code for all three is (almost) the same. 

First step is to download the MySQL Java _driver_.  A _driver_ is kind of like an adapter that allows two pieces of software to talk to once another. The MySQL driver is a Java library that allows your application code to talk to the MySQL database.

The task here is to add the latest version of MySQL to the `pom.xml`.

**Comment by patrickatcw** [comment]
added Java Database Connectivity mysql to the pom.xml
