### ISSUE TITLE
JDBC Part II: Use Java to Query MySQL

### ISSUE THREAD

**Issue by rpmartz** [patrickatcw/JavaBanco#22]
This task is to use the JDBC API to connect to the database. We'll keep it simple for now and just say that the only think we'll do with the results is print them out to the console. In other words, just iterate over your `ResultSet` and print out each row using `System.out.println()`. 

There are plenty of tutorials for JDBC, here are two: https://docs.oracle.com/javase/tutorial/jdbc/basics/index.html  and http://www.vogella.com/tutorials/MySQLJava/article.html

**Comment by patrickatcw** [comment]
all good daddy o
