### ISSUE TITLE
JDBC Part III: Update data with JDBC

### ISSUE THREAD

**Issue by rpmartz** [patrickatcw/JavaBanco#23]
Now that we've learned how to read data from the database using Java, it's time to update it. 

This will be the last task that we use the console and `System.out.println()` statements for; after this we're going to move to Spring and start interacting with our website via a webpage. 

Write a program that asks the user for two things from the command line: an account number and an amount, and then use that information to update the balance of that account in the database.

One little wrinkle I want you to handle is to actually validate that the account number is actually an account number in the database. If it isn't, your program should tell the user that and not proceed until the user enters a valid account number.

After you do the update, print out a message confirming that the update succeeded and what the new account balance is.

**Comment by patrickatcw** [comment]
holy cow daddy o, i dun dun it. i am sure my desire to add input involves a change in string sql
