### ISSUE TITLE
Spring Part I: Display a welcome to JavaBanco webpage

### ISSUE THREAD

**Issue by rpmartz** [patrickatcw/JavaBanco#24]
Ok, take a deep breath because we're going off the deep end here. Time to start getting our arms around the Spring Framework. Spring is an absolute monster framework that has all kinds of features for building Very Serious Enterprise Business Applications. Don't waste your time trying to understand every nook and cranny of Spring, it can't be done. Focus on the core concepts of Spring MVC and dependency injection for now, and you can pick up the rest of what you need as you go.

Here's a tutorial of how to use Spring MVC to serve a webpage: https://spring.io/guides/gs/serving-web-content/

I want you to go through that tutorial and then update JavaBanco to serve a webpage. It can be really simple for now, just a page that displays `<h2>Welcome to JavaBanco</h2>` is fine.

**Comment by rpmartz** [comment]
It's up to you - you can either update the `pom.xml` and your `src/main/java` directory manually or you can head over to `start.spring.io` and have it make a new project for you to be able to use Spring Boot.

**Comment by patrickatcw** [comment]
all done here , spring is some pretty powerful stuff
