### ISSUE TITLE
Spring Part II: Take a form submission

### ISSUE THREAD

**Issue by rpmartz** [patrickatcw/JavaBanco#25]
In one of the earlier tasks, we took input from the user at the command line with an account number and an amount and then updated the database with that info.

We're going to do the same thing here but now we're going to get that info via a webpage, like you would with a real bank.

Go through this getting started guide: https://spring.io/guides/gs/handling-form-submission/ and then update JavaBanco to have an HTML form that takes an account number and amount to update via an HTML form.

**Comment by patrickatcw** [comment]
done
