### ISSUE TITLE
Add additional check to `transfer()` method.

### ISSUE THREAD

**Issue by rpmartz** [patrickatcw/JavaBanco#9]
We're going to improve the `transfer()` method a little bit and learn a new technique called Test Driven Design (TDD) in the process. 

TDD, sometimes called test-first design, is just a technique where you write tests for code before you write the implementation of the code. If you look around the internet, you'll see a lot of strong opinions about it, with some saying you should always do TDD and not doing it is wrong. Others say it's a waste of time. Like any technique, it has its place. 

I like it, and I use it, but I don't always do it. The biggest benefits, in my opinion, are that it forces you to actually write tests, and it can help you to make sure you design your code to be testable. All too often, "I'll write tests later" turns into "I never wrote any tests." If you write your tests before production code, your code will always have a certain amount of test coverage, which is a good thing.

Another place TDD really shines is for bug fixes. Let's say your boss comes to you and says that some piece of code is adding `"9A"` to the end of everything in prints out. Well, you can write a test that should be passing but is not passing beacause of the bug, fix the bug, then when you re-run your tests, if you fixed the bug, they should pass.

Anyway, enough theory for now. 

You actually started doing this in your other JavaBankAccount project so it should be pretty straightforward, but I want you to add the same checks to the `transfer` method so that you cannot process a transfer for an amount that's greater than the `accountToDebit`'s current balance. 

The difference is, I want you to write a test for this first, and commit that test when it's failing before you add the check in the `transfer` method.

**Comment by patrickatcw** [comment]
created test, failing, then made changes in TransferManager to pass test
